language: minimal

# broken:
#   - PKG=electrs STABLE=0

# Retry installing nix due to nondeterministic error
#   Fatal error: glibc detected an invalid stdio handle
# see:
#   https://github.com/nh2/static-haskell-nix/pull/27#issuecomment-502652181
#   https://github.com/nixos/nix/issues/2733
install: |
  (for i in {1..5}; do bash <(curl https://nixos.org/nix/install) && exit 0; done; exit 1)
  . /home/travis/.nix-profile/etc/profile.d/nix.sh
  nix-env -iA cachix -f https://cachix.org/api/v1/install
  cachix use nix-bitcoin
  [ $STABLE -eq 1 ] && export NIX_PATH="nixpkgs=$(nix eval --raw -f pkgs/nixpkgs-pinned.nix nixpkgs)"
  [ $STABLE -eq 0 ] && export NIX_PATH="nixpkgs=$(nix eval --raw -f pkgs/nixpkgs-pinned.nix nixpkgs-unstable)"
  VER="$(nix eval nixpkgs.lib.version)"
env:
  matrix:
  - PKG=nodeinfo STABLE=1
  - PKG=hwi STABLE=1
  - PKG=hwi STABLE=0
  - PKG=lightning-charge STABLE=1
  - PKG=lightning-charge STABLE=0
  - PKG=nanopos STABLE=1
  - PKG=nanopos STABLE=0
  - PKG=spark-wallet STABLE=1
  - PKG=elementsd STABLE=1
  - PKG=elementsd STABLE=0
  - PKG=electrs STABLE=1
script: |
  printf '%s (%s)\n' "$NIX_PATH" "$VER"
  nix-build -A $PKG
